services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules # Previene problemi con i node_modules locali
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - randomfilm_net
networks:
  randomfilm_net:
    external: true